### PR TITLE
✂️ Remove duplicate H1 renders

### LINKED ISSUE #7: Initial H1 heading gets duplicated
### Describe the bug

**context**
If the first cell has an H1 heading, it gets doubly-rendered (the duplicate also shows up in the outline view):

image

(this screenshot shows the same notebook opened on the left with the default renderer and on the right with this one).

### Reproduce the bug

Make the first cell have a `# H1 heading`.

### List your environment

_No response_

### PR DESCRIPTION
**Pull request by fwkoch**
Pretty sure this is as simple as setting `removeHeading: true` when parsing frontmatter.

resolves #7

### CODE REVIEW

File: src/myst.ts [hunk 1]
```diff
@@ -66,7 +66,7 @@ export function parseContent(notebook: StaticNotebook): void {
     mdast.children[0]?.children[0] as any,
     {
       removeYaml: true,
-      removeHeading: false
+      removeHeading: true
```
Comment (rowanc1) [inline src/myst.ts:69]: Looks good!

**Review by rowanc1 — APPROVED** [review]
The small changes look great, and does indeed remove the duplicate header.
